package pl.shoeshop.shoeshop;

public enum BrandType {
    NIKE, REEBOK, ADIDAS, KAZAR, WOJAS, OCHNIK,
    CLARKS, CONVERSE, ECCO, EMU, FREEWEAR,
    GINO_ROSSI, GUESS, HELLY_HANSEN, JORDAN,
    LACOSTE, NEW_BALANCE, ONEILL, POLO_RALPH_LAUREN,
    PUMA, ROXY, SALOMON, SYMBIOSIS, TIMBERLAND,
    TOMMY_HILFIGER, TOMS, UMBRO, VANS;
}
